"""
Django settings for drilling_scheduler project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Persist the secret key so sessions survive server restarts
import secrets
import string

def load_or_create_secret_key():
    env_key = os.getenv('SECRET_KEY')
    if env_key:
        return env_key
    key_file = BASE_DIR / '.django_secret_key'
    if key_file.exists():
        return key_file.read_text().strip()
    alphabet = string.ascii_letters + string.digits + '!@#$%^&*(-_=+)'
    new_key = ''.join(secrets.choice(alphabet) for _ in range(64))
    key_file.write_text(new_key)
    try:
        os.chmod(key_file, 0o600)
    except Exception:
        pass
    return new_key

SECRET_KEY = load_or_create_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,0.0.0.0,10.212.64.16').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'scheduler',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise for static files
    'scheduler.error_middleware.GracefulErrorMiddleware',  # MUST be above SessionMiddleware to catch SessionInterrupted
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'scheduler.activity_middleware.ActivityTrackingMiddleware',  # User activity tracking
]

ROOT_URLCONF = 'drilling_scheduler.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'scheduler.context_processors.external_app_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'drilling_scheduler.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL', f'sqlite:///{BASE_DIR}/db.sqlite3')

if DATABASE_URL.startswith('postgresql://') or DATABASE_URL.startswith('postgres://'):
    import dj_database_url  # type: ignore[import-not-found]
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=60)
    }
    # Disable server-side cursors to avoid issues with connection pooling in threads
    DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True
elif DATABASE_URL.startswith('sqlite:///'):
    # Support absolute paths (sqlite:////app/data/db.sqlite3) and relative paths
    db_path = DATABASE_URL[len('sqlite:///'):]
    if not db_path.startswith('/'):
        db_path = BASE_DIR / db_path
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': db_path,
            'OPTIONS': {
                'timeout': 30,  # Wait up to 30 seconds for database locks to clear
            }
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                'timeout': 30,
            }
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# Authentication backends - LDAP + Django
# LDAP backend tries first, then falls back to Django ModelBackend for admin users
AUTHENTICATION_BACKENDS = [
    'scheduler.backends.LDAPBackend',  # LDAP authentication for authorized users
    'django.contrib.auth.backends.ModelBackend',  # Django DB authentication for admin users
]

# LDAP Configuration - loaded from .env file
LDAP_SERVER = os.getenv('LDAP_SERVER', 'ldap://10.205.48.230:389')
LDAP_BASE_DN = os.getenv('LDAP_BASE_DN', 'DC=ONGC,DC=ONGCGroup,DC=co,DC=in')
LDAP_USE_SSL = os.getenv('LDAP_USE_SSL', 'False').lower() == 'true'
LDAP_VERIFY_SSL = os.getenv('LDAP_VERIFY_SSL', 'False').lower() == 'true'
LDAP_DOMAIN = os.getenv('LDAP_DOMAIN', 'ongcgroup.co.in')
LDAP_CA_CERT_PATH = os.getenv('LDAP_CA_CERT_PATH', None)

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Static files finders - ensure all static files are collected properly
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# WhiteNoise configuration for efficient static file serving
# CompressedStaticFilesStorage: compresses files but does NOT validate source map
# references in JS/CSS (avoids MissingFileError on .map files not present in repo)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ==============================================================================
# VIDEO STREAMING CONFIGURATION
# ==============================================================================
# These settings optimize video streaming for network delivery

# Chunk size for video streaming (256KB for smooth network delivery)
VIDEO_STREAM_CHUNK_SIZE = 256 * 1024  # 256KB

# Cache settings for video files
VIDEO_CACHE_MAX_AGE = 86400  # 24 hours

# Video processing settings
VIDEO_PROCESSING = {
    # Compression quality (0-51, lower = better quality, 23 is default)
    'COMPRESSION_CRF': 23,
    # Encoding preset (ultrafast, fast, medium, slow, veryslow)
    'COMPRESSION_PRESET': 'medium',
    # Audio bitrate for compressed videos
    'AUDIO_BITRATE': '128k',
    # Minimum file size (MB) to trigger compression
    'COMPRESSION_MIN_SIZE_MB': 50,
    # Minimum file size (MB) to generate HLS streams
    'HLS_MIN_SIZE_MB': 100,
    # HLS segment duration in seconds
    'HLS_SEGMENT_DURATION': 6,
    # Target resolution for compressed versions
    'TARGET_HEIGHT': 720,
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'scheduler.pagination.FlexiblePageNumberPagination',
    'PAGE_SIZE': 100,
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

CORS_ALLOW_ALL_ORIGINS = DEBUG

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 1024  # 1GB for video uploads
DATA_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 1024  # 1GB for video uploads

# ===== SECURITY SETTINGS =====
# These settings address Django security warnings and improve security posture

# Determine if we're in a secure environment (HTTPS)
USE_HTTPS = os.getenv('USE_HTTPS', 'False').lower() == 'true'

# Additional security headers
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# Session security - PERMANENT SESSIONS UNTIL EXPLICIT LOGOUT
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 31536000  # 365 days (1 year in seconds) - essentially permanent
SESSION_SAVE_EVERY_REQUEST = True  # Extend session on every request
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Keep user logged in even after browser close
SESSION_COOKIE_NAME = 'idrs_sessionid'  # Unique session cookie name to avoid conflicts with other Django apps
CSRF_COOKIE_NAME = 'idrs_csrftoken'
SESSION_COOKIE_PATH = '/'  # Explicit path
SESSION_COOKIE_SAMESITE = 'Lax'  # Prevent CSRF attacks
SESSION_COOKIE_DOMAIN = None  # Allow for localhost and other domains
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Use database backend for reliability

# Security settings for HTTPS (W004, W008)
if USE_HTTPS:
    # HTTP Strict Transport Security (HSTS)
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Force HTTPS redirects
    SECURE_SSL_REDIRECT = True
    
    # Secure cookies (W012, W016)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Additional HTTPS security
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    
else:
    # Development settings (less secure but functional for local development)
    SECURE_HSTS_SECONDS = 0
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# CSRF protection - CRITICAL FOR PRODUCTION
# DO NOT use CSRF_USE_SESSIONS as it can cause token length issues
CSRF_COOKIE_HTTPONLY = False  # Must be False for JavaScript to read token
CSRF_USE_SESSIONS = False  # Keep False - session-based tokens cause issues
CSRF_COOKIE_SAMESITE = 'Lax'  # Lax works better for cross-origin requests
CSRF_COOKIE_NAME = 'idrs_csrftoken'  # Unique CSRF cookie name to avoid conflicts with other Django apps
CSRF_COOKIE_PATH = '/'  # Explicit path

# CSRF Trusted Origins - Add your VM IP/domain here
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8011',
    'http://127.0.0.1:8011',
    'http://localhost',
    'http://127.0.0.1',
    'http://10.212.64.16:8011',
    'http://10.212.64.16',
    # Add additional IPs/domains if needed:
    # 'http://your-vm-hostname:8011',
]

# Additional security middleware should be enabled in production
if not DEBUG:
    # Add security middleware for production
    MIDDLEWARE.insert(1, 'django.middleware.security.SecurityMiddleware')

# Logging configuration for security monitoring
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
        'ldap_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'ldap_auth.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django.security': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'] if DEBUG else ['file'],
            'level': 'INFO',
            'propagate': False,
        },
        'ldap_auth': {
            'handlers': ['ldap_file', 'console'],
            'level': os.getenv('LDAP_LOG_LEVEL', 'DEBUG'),
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
os.makedirs(BASE_DIR / 'logs', exist_ok=True)

# Authentication settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
# LOGOUT_REDIRECT_URL = '/login/'  # Commented out to show custom logout page instead

# External App Configuration - Default values (can be overridden in Django Admin)
EXTERNAL_APP_URL = os.getenv('EXTERNAL_APP_URL', 'http://127.0.0.1:8000')
EXTERNAL_APP_NAME = os.getenv('EXTERNAL_APP_NAME', 'Submit Bug/Enhancement')

# Production-specific settings
if not DEBUG:
    # Note: To disable admin in production, remove 'django.contrib.admin' from INSTALLED_APPS
    # and remove admin URLs from urls.py
    pass
    
    # More restrictive CORS settings for production
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        # Add your production domains here
        # "https://yourdomain.com",
    ]
    
    # Cache settings for production
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }
