# Generated by Django 5.2.5 on 2025-08-18 06:05

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Rig identifier (e.g., JOHN-1000-29)', max_length=50, unique=True)),
                ('rig_type', models.CharField(choices=[('Mobile', 'Mobile'), ('Fixed', 'Fixed')], max_length=10)),
                ('start_date', models.DateField(help_text='Rig availability start date')),
                ('end_date', models.DateField(help_text='Rig availability end date')),
                ('rig_capacity_hp', models.IntegerField(help_text='Rig capacity in horsepower', validators=[django.core.validators.MinValueValidator(1)])),
                ('daily_cost_inr', models.DecimalField(decimal_places=2, help_text='Daily cost in INR', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('drilling_capacity_m', models.IntegerField(help_text='Maximum drilling depth in meters', validators=[django.core.validators.MinValueValidator(1)])),
                ('mobilization_time_days', models.CharField(blank=True, help_text="Time required for mobilization (e.g., 'Nil', '5 days')", max_length=10, null=True)),
                ('maintenance_schedule', models.CharField(blank=True, help_text='Maintenance schedule information', max_length=100, null=True)),
                ('crew_availability', models.CharField(choices=[('OK', 'OK'), ('NOT_OK', 'Not OK')], default='OK', max_length=10)),
                ('hpht_suitability', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', help_text='High Pressure High Temperature suitability', max_length=1)),
                ('ilm_cost_fixed', models.DecimalField(decimal_places=2, help_text='Inter Location Movement fixed cost', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('ilm_cost_per_km', models.DecimalField(decimal_places=2, help_text='ILM cost per kilometer', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('ilm_cost_cluster', models.DecimalField(decimal_places=2, help_text='ILM cost for cluster operations', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('bop_stack', models.IntegerField(help_text='BOP Stack capacity', validators=[django.core.validators.MinValueValidator(1)])),
                ('tds_availability', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', help_text='Top Drive System availability', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Drilling Rig',
                'verbose_name_plural': 'Drilling Rigs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Schedule name/description', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_drilling_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Total drilling cost in INR', max_digits=15, null=True)),
                ('total_ilm_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Total ILM cost in INR', max_digits=15, null=True)),
                ('project_end_date', models.DateField(blank=True, help_text='Calculated project completion date', null=True)),
                ('unassigned_wells_count', models.IntegerField(default=0, help_text="Number of wells that couldn't be assigned")),
                ('solver_status', models.CharField(blank=True, help_text='OR-Tools solver status', max_length=20, null=True)),
                ('solve_time_seconds', models.FloatField(blank=True, help_text='Time taken to solve in seconds', null=True)),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sn', models.IntegerField(help_text='Serial number', unique=True)),
                ('asset_id', models.CharField(help_text='Asset identifier', max_length=50)),
                ('name', models.CharField(help_text='Well name', max_length=50)),
                ('well_type', models.CharField(choices=[('EXP', 'Exploration'), ('Dev', 'Development')], max_length=3)),
                ('well_profile', models.CharField(choices=[('DI', 'Directional'), ('VE', 'Vertical'), ('SD', 'Sidetrack')], max_length=2)),
                ('depth', models.IntegerField(help_text='Well depth in meters', validators=[django.core.validators.MinValueValidator(1)])),
                ('rig_capacity_required_hp', models.IntegerField(help_text='Required rig capacity in HP', validators=[django.core.validators.MinValueValidator(1)])),
                ('drl_days', models.IntegerField(help_text='Drilling days required', validators=[django.core.validators.MinValueValidator(0)])),
                ('pt_days', models.IntegerField(help_text='Post-drilling testing days', validators=[django.core.validators.MinValueValidator(0)])),
                ('duration', models.IntegerField(help_text='Total duration in days', validators=[django.core.validators.MinValueValidator(1)])),
                ('latitude', models.DecimalField(decimal_places=6, help_text='GPS latitude', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='GPS longitude', max_digits=10)),
                ('rtd', models.DateField(help_text='Ready To Drill date')),
                ('bop_stack', models.IntegerField(help_text='Required BOP Stack capacity', validators=[django.core.validators.MinValueValidator(1)])),
                ('tds_requirement', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], help_text='Top Drive System requirement', max_length=1)),
                ('footprint', models.CharField(choices=[('Mobile', 'Mobile'), ('Fixed', 'Fixed')], help_text='Required rig footprint type', max_length=10)),
                ('preferred_rig', models.CharField(blank=True, help_text='Preferred rig for this well', max_length=50, null=True)),
                ('expected_potential', models.CharField(blank=True, help_text='Expected well potential', max_length=20, null=True)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Well',
                'verbose_name_plural': 'Wells',
                'ordering': ['sn'],
            },
        ),
        migrations.CreateModel(
            name='UnassignedWell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text="Reason why the well couldn't be assigned")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unassigned_wells', to='scheduler.schedule')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unassigned_schedules', to='scheduler.well')),
            ],
            options={
                'verbose_name': 'Unassigned Well',
                'verbose_name_plural': 'Unassigned Wells',
                'ordering': ['well__sn'],
                'unique_together': {('schedule', 'well')},
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('well_start_date', models.DateField(help_text='Calculated well start date')),
                ('well_end_date', models.DateField(help_text='Calculated well end date')),
                ('rtd_check', models.CharField(choices=[('OK', 'OK'), ('NOK', 'Not OK')], help_text='RTD date validation', max_length=3)),
                ('well_start_check', models.CharField(choices=[('OK', 'OK'), ('NOK', 'Not OK')], help_text='Well start date validation', max_length=3)),
                ('well_end_check', models.CharField(choices=[('OK', 'OK'), ('NOK', 'Not OK')], help_text='Well end date validation', max_length=3)),
                ('depth_check', models.CharField(choices=[('OK', 'OK'), ('NOK', 'Not OK')], help_text='Depth capability check', max_length=3)),
                ('hp_check', models.CharField(choices=[('OK', 'OK'), ('NOK', 'Not OK')], help_text='Horsepower check', max_length=3)),
                ('bop_check', models.CharField(choices=[('OK', 'OK'), ('NOK', 'Not OK')], help_text='BOP stack check', max_length=3)),
                ('tds_check', models.CharField(choices=[('OK', 'OK'), ('NOK', 'Not OK')], help_text='TDS availability check', max_length=3)),
                ('rig_type_check', models.CharField(choices=[('OK', 'OK'), ('NOK', 'Not OK')], help_text='Rig type compatibility check', max_length=3)),
                ('drilling_cost', models.DecimalField(decimal_places=2, help_text='Drilling cost for this assignment', max_digits=12)),
                ('ilm_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='ILM cost to reach this well', max_digits=12)),
                ('sequence_order', models.IntegerField(help_text="Order of this well in the rig's sequence")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='scheduler.rig')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='scheduler.schedule')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='scheduler.well')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['rig__name', 'sequence_order'],
                'unique_together': {('schedule', 'well')},
            },
        ),
    ]
