# Generated by Django 5.1.5 on 2025-09-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rig',
            name='asset_id',
            field=models.CharField(blank=True, help_text='Asset/Location identifier', max_length=50, null=True),
        ),
    ]
