# Generated by Django 5.1.5 on 2025-09-30 04:09

import scheduler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_rig_asset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='financial_year',
            field=models.CharField(db_index=True, default=scheduler.models.get_current_financial_year, help_text='Financial Year (e.g., 2024-2025, 2025-2026)', max_length=9),
        ),
    ]
