# Generated by Django 5.1.5 on 2025-10-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_schedule_financial_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='actual_end_date',
            field=models.DateField(blank=True, help_text='Actual date when drilling completed for this well', null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='actual_start_date',
            field=models.DateField(blank=True, help_text='Actual date when drilling started for this well', null=True),
        ),
    ]
