# Generated by Django 5.1.5 on 2025-10-15 05:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_add_actual_dates_to_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleRig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_schedules', to='scheduler.rig')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_rigs', to='scheduler.schedule')),
            ],
            options={
                'verbose_name': 'Schedule Rig',
                'verbose_name_plural': 'Schedule Rigs',
                'unique_together': {('schedule', 'rig')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleWell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_wells', to='scheduler.schedule')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_schedules', to='scheduler.well')),
            ],
            options={
                'verbose_name': 'Schedule Well',
                'verbose_name_plural': 'Schedule Wells',
                'unique_together': {('schedule', 'well')},
            },
        ),
    ]
