# Generated by Django 5.1.5 on 2025-10-15 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_schedulerig_schedulewell'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='branch_type',
            field=models.CharField(blank=True, help_text="Type of branching: 'reschedule', 'add_well', 'delete_well', etc.", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='parent_schedule',
            field=models.ForeignKey(blank=True, help_text='Parent schedule if this is derived from another schedule', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_schedules', to='scheduler.schedule'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='version_number',
            field=models.IntegerField(default=1, help_text='Version number within the schedule family'),
        ),
    ]
