# Generated by Django 4.2.7 on 2025-10-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_schedule_branch_type_schedule_parent_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='original_planned_end',
            field=models.DateField(blank=True, help_text='Original planned end date before actual dates were locked', null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='original_planned_start',
            field=models.DateField(blank=True, help_text='Original planned start date before actual dates were locked', null=True),
        ),
    ]
