# Generated by Django 5.1.5 on 2025-12-08 15:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_add_original_planned_dates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Location code/identifier (e.g., ASSET-1, FIELD-A)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Full name of the location', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the location', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this location is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='rig',
            name='asset_id',
            field=models.CharField(blank=True, help_text='Asset/Location identifier (legacy field)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='well',
            name='asset_id',
            field=models.CharField(help_text='Asset identifier (legacy field)', max_length=50),
        ),
        migrations.AddField(
            model_name='rig',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location where this rig is assigned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rigs', to='scheduler.location'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location this schedule belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='scheduler.location'),
        ),
        migrations.AddField(
            model_name='well',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location where this well is located', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wells', to='scheduler.location'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_all_locations', models.BooleanField(default=False, help_text='If True, user can view data from all locations (like an admin)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, help_text='Location this user belongs to. If empty, user can see all locations (admin).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='scheduler.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
