# Generated by Django 5.1.5 on 2025-12-08 15:54

from django.db import migrations


def migrate_asset_ids_to_locations(apps, schema_editor):
    """
    Create Location objects from existing unique asset_ids in Wells and Rigs,
    then link the wells, rigs, and schedules to their respective locations.
    """
    Location = apps.get_model('scheduler', 'Location')
    Well = apps.get_model('scheduler', 'Well')
    Rig = apps.get_model('scheduler', 'Rig')
    Schedule = apps.get_model('scheduler', 'Schedule')
    
    # Get all unique asset_ids from wells
    well_asset_ids = set(Well.objects.exclude(asset_id__isnull=True).exclude(asset_id='').values_list('asset_id', flat=True))
    
    # Get all unique asset_ids from rigs
    rig_asset_ids = set(Rig.objects.exclude(asset_id__isnull=True).exclude(asset_id='').values_list('asset_id', flat=True))
    
    # Combine all unique asset_ids
    all_asset_ids = well_asset_ids.union(rig_asset_ids)
    
    # Create Location objects for each unique asset_id
    location_map = {}
    for asset_id in all_asset_ids:
        location, created = Location.objects.get_or_create(
            code=asset_id,
            defaults={
                'name': f'{asset_id} Location',
                'description': f'Auto-created location for asset_id: {asset_id}',
                'is_active': True
            }
        )
        location_map[asset_id] = location
    
    # Link wells to locations
    for well in Well.objects.exclude(asset_id__isnull=True).exclude(asset_id=''):
        if well.asset_id in location_map:
            well.location = location_map[well.asset_id]
            well.save()
    
    # Link rigs to locations
    for rig in Rig.objects.exclude(asset_id__isnull=True).exclude(asset_id=''):
        if rig.asset_id in location_map:
            rig.location = location_map[rig.asset_id]
            rig.save()
    
    # Link schedules to locations based on their wells' locations
    for schedule in Schedule.objects.all():
        # Get the first well's location from the schedule's assignments
        assignment = schedule.assignments.first()
        if assignment and assignment.well and assignment.well.location:
            schedule.location = assignment.well.location
            schedule.save()


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by setting all location fields to None.
    """
    Well = apps.get_model('scheduler', 'Well')
    Rig = apps.get_model('scheduler', 'Rig')
    Schedule = apps.get_model('scheduler', 'Schedule')
    Location = apps.get_model('scheduler', 'Location')
    
    Well.objects.all().update(location=None)
    Rig.objects.all().update(location=None)
    Schedule.objects.all().update(location=None)
    # Don't delete locations as they may have been manually created


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_location_alter_rig_asset_id_alter_well_asset_id_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_asset_ids_to_locations, reverse_migration),
    ]
