# Generated by Django 5.1.5 on 2025-12-12 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_migrate_asset_ids_to_locations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rig',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was soft-deleted', null=True),
        ),
        migrations.AddField(
            model_name='rig',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rig',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. If True, this record is considered deleted.'),
        ),
        migrations.AddField(
            model_name='well',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the record was soft-deleted', null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='well',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag. If True, this record is considered deleted.'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='rig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='scheduler.rig'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='scheduler.well'),
        ),
        migrations.AlterField(
            model_name='schedulerig',
            name='rig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selected_schedules', to='scheduler.rig'),
        ),
        migrations.AlterField(
            model_name='schedulewell',
            name='well',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selected_schedules', to='scheduler.well'),
        ),
    ]
