# Generated by Django 5.1.5 on 2025-12-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_externalappsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalappsetting',
            name='secret_key',
            field=models.CharField(default='iDRS_secret_key_12345', help_text='Secret key for HMAC signature generation. MUST match AppSense configuration.', max_length=255),
        ),
    ]
