# Generated by Django 5.1.5 on 2026-01-06 07:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_externalappsetting_secret_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StagedWell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.CharField(help_text='Asset identifier', max_length=50)),
                ('name', models.CharField(help_text='Well name', max_length=50)),
                ('well_type', models.CharField(choices=[('EXP', 'Exploration'), ('Dev', 'Development')], max_length=3)),
                ('depth', models.IntegerField(help_text='Well depth in meters', validators=[django.core.validators.MinValueValidator(1)])),
                ('latitude', models.DecimalField(decimal_places=6, help_text='GPS latitude', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='GPS longitude', max_digits=10)),
                ('rtd', models.DateField(help_text='Ready To Drill date')),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=6)),
                ('well_profile', models.CharField(blank=True, choices=[('DI', 'Directional'), ('VE', 'Vertical'), ('SD', 'Sidetrack')], help_text='Well profile type - to be completed by user', max_length=2, null=True)),
                ('rig_capacity_required_hp', models.IntegerField(blank=True, help_text='Required rig capacity in HP - to be completed by user', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('drl_days', models.IntegerField(blank=True, help_text='Drilling days required - to be completed by user', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('pt_days', models.IntegerField(blank=True, help_text='Post-drilling testing days - to be completed by user', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration', models.IntegerField(blank=True, help_text='Total duration in days - to be completed by user', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('bop_stack', models.IntegerField(blank=True, help_text='Required BOP Stack capacity - to be completed by user', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('tds_requirement', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], help_text='Top Drive System requirement - to be completed by user', max_length=1, null=True)),
                ('footprint', models.CharField(blank=True, choices=[('Mobile', 'Mobile'), ('Fixed', 'Fixed')], help_text='Required rig footprint type - to be completed by user', max_length=10, null=True)),
                ('preferred_rig', models.CharField(blank=True, help_text='Preferred rig for this well - to be completed by user', max_length=50, null=True)),
                ('expected_potential', models.CharField(blank=True, help_text='Expected well potential - to be completed by user', max_length=20, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Completion'), ('COMPLETED', 'Ready to Import'), ('IMPORTED', 'Imported to Wells')], default='PENDING', help_text='Current status of staged well', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, help_text='User who completed the additional fields', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_staged_wells', to=settings.AUTH_USER_MODEL)),
                ('imported_well', models.ForeignKey(blank=True, help_text='The final Well record created from this staged well', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_source', to='scheduler.well')),
                ('location', models.ForeignKey(blank=True, help_text='Location where this well is located', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_wells', to='scheduler.location')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded this well', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_staged_wells', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staged Well',
                'verbose_name_plural': 'Staged Wells',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
