# Generated by Django 5.1.5 on 2026-01-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_stagedwell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagedwell',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude - can be filled manually if missing from CSV', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stagedwell',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude - can be filled manually if missing from CSV', max_digits=10, null=True),
        ),
    ]
