# Generated by Django 5.1.5 on 2026-01-07 07:29

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_allow_null_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagedwell',
            name='field_name',
            field=models.CharField(blank=True, db_index=True, help_text='Field name - used for benchmark lookup', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='well',
            name='field_name',
            field=models.CharField(blank=True, db_index=True, help_text='Field name - used for benchmark lookup', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DrillingBenchmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pool', models.CharField(help_text='Pool name (e.g., Assam)', max_length=100)),
                ('well_category', models.CharField(choices=[('New Well', 'New Well'), ('Workover', 'Workover'), ('Sidetrack', 'Sidetrack')], help_text='Category of well', max_length=50)),
                ('depth_range', models.CharField(help_text='Depth range (e.g., 2500-3000, >4000)', max_length=50)),
                ('field', models.CharField(db_index=True, help_text='Field name', max_length=100)),
                ('drilling_depth', models.IntegerField(help_text='Representative drilling depth in meters', validators=[django.core.validators.MinValueValidator(1)])),
                ('benchmark_days', models.DecimalField(decimal_places=2, help_text='Benchmark drilling days', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Drilling Benchmark',
                'verbose_name_plural': 'Drilling Benchmarks',
                'ordering': ['pool', 'field', 'well_category', 'depth_range'],
                'unique_together': {('pool', 'well_category', 'depth_range', 'field')},
            },
        ),
        migrations.CreateModel(
            name='RigBuildingNorm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rig_type', models.CharField(choices=[('TL', 'Truck Loaded'), ('SEMI', 'Semi'), ('LR', 'Land Rig')], help_text='Type of rig', max_length=50)),
                ('condition', models.CharField(choices=[('Assembled', 'Assembled'), ('Dismantled', 'Dismantled'), ('Partial', 'Partial')], help_text='Rig condition', max_length=50)),
                ('norm_time_days', models.DecimalField(decimal_places=2, help_text='Standard norm time in days', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('adjustment_factor', models.DecimalField(decimal_places=2, default=1.0, help_text='Adjustment factor for calculations', max_digits=4)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this norm', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rig Building Norm',
                'verbose_name_plural': 'Rig Building Norms',
                'ordering': ['rig_type', 'condition'],
                'unique_together': {('rig_type', 'condition')},
            },
        ),
    ]
