# Generated by Django 5.1.5 on 2026-01-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_stagedwell_field_name_well_field_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drillingbenchmark',
            name='well_category',
            field=models.CharField(choices=[('DI', 'Directional'), ('VE', 'Vertical'), ('SD', 'Sidetrack')], help_text='Category of well', max_length=50),
        ),
    ]
