# Generated by Django 5.1.5 on 2026-01-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_update_rigbuildingnorm'),
    ]

    operations = [
        migrations.AddField(
            model_name='rigbuildingnorm',
            name='rig_type',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('Mobile', 'Mobile')], default='Fixed', help_text='Type of rig (Fixed or Mobile)', max_length=20),
        ),
        migrations.AddField(
            model_name='rigbuildingnorm',
            name='top_drive',
            field=models.BooleanField(default=False, help_text='Whether this rig has top drive capability'),
        ),
    ]
