# Generated by Django 5.1.5 on 2026-01-10 07:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0018_rigbuildingnorm_rig_type_rigbuildingnorm_top_drive'),
    ]

    operations = [
        migrations.CreateModel(
            name='RigBuildingAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition', models.CharField(help_text="Description of the condition/scenario (e.g., 'Rig dragged within 25m radius for adjacent well')", max_length=500)),
                ('category', models.CharField(choices=[('cluster_movement', 'Cluster Movement'), ('transportation', 'Transportation'), ('equipment', 'Equipment Related'), ('weather', 'Weather/Monsoon'), ('other', 'Other')], default='other', help_text='Category of this adjustment rule', max_length=50)),
                ('adjustment_type', models.CharField(choices=[('replace', 'Replace Base Norm'), ('add', 'Add to Base Norm'), ('included', 'Included (No Extra)'), ('per_unit', 'Per Unit Addition'), ('conversion', 'Conversion Rule'), ('conditional', 'Conditional Rule')], default='add', help_text='How this adjustment is applied', max_length=20)),
                ('adjustment_value', models.DecimalField(blank=True, decimal_places=2, help_text='Numeric value for the adjustment (days, conversion factor, etc.)', max_digits=10, null=True)),
                ('adjustment_display', models.CharField(help_text="Human-readable adjustment display (e.g., '+1 day', '2 days', '0.7 ratio')", max_length=100)),
                ('unit', models.CharField(blank=True, help_text="Unit for per-unit adjustments (e.g., '50 km')", max_length=50, null=True)),
                ('min_distance', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum distance in meters for distance-based rules', max_digits=10, null=True)),
                ('max_distance', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum distance in meters for distance-based rules', max_digits=10, null=True)),
                ('applies_to_rig_type', models.CharField(blank=True, help_text='Rig type this rule applies to (Mobile, Fixed, Type-I, or blank for all)', max_length=50, null=True)),
                ('max_depth', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum well depth in meters for depth-based rules', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or clarifications', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is currently active')),
                ('priority', models.IntegerField(default=0, help_text='Priority for rule application (higher = applied first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rig Building Adjustment',
                'verbose_name_plural': 'Rig Building Adjustments',
                'ordering': ['category', 'priority', 'condition'],
            },
        ),
    ]
