# Generated by Django 5.1.5 on 2026-01-10 07:55

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0019_rigbuildingadjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationNorm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(help_text='Name of the operation', max_length=200, unique=True)),
                ('norm_rule', models.CharField(help_text='Norm or rule for the operation', max_length=200)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['operation'],
            },
        ),
        migrations.CreateModel(
            name='CasingNorm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('depth_start', models.IntegerField(help_text='Start depth in meters', validators=[django.core.validators.MinValueValidator(0)])),
                ('depth_end', models.IntegerField(help_text='End depth in meters', validators=[django.core.validators.MinValueValidator(0)])),
                ('additional_days', models.DecimalField(decimal_places=2, help_text='Additional norm time in days for casing lowering + cementation', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['depth_start'],
                'unique_together': {('depth_start', 'depth_end')},
            },
        ),
        migrations.CreateModel(
            name='CoringNorm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('depth_start', models.IntegerField(help_text='Start depth in meters', validators=[django.core.validators.MinValueValidator(0)])),
                ('depth_end', models.IntegerField(help_text='End depth in meters', validators=[django.core.validators.MinValueValidator(0)])),
                ('additional_days', models.DecimalField(decimal_places=2, help_text='Additional norm time in days for one core', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['depth_start'],
                'unique_together': {('depth_start', 'depth_end')},
            },
        ),
        migrations.CreateModel(
            name='DailyDrillingRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.CharField(help_text='Asset identifier (e.g., Mehsana)', max_length=100)),
                ('depth_start', models.IntegerField(help_text='Start depth in meters', validators=[django.core.validators.MinValueValidator(0)])),
                ('depth_end', models.IntegerField(help_text='End depth in meters', validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.CharField(help_text='Location name (e.g., Akholjuni, Anklav)', max_length=200)),
                ('per_day_depth', models.DecimalField(decimal_places=2, help_text='Meters drilled per day', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['asset_id', 'location', 'depth_start'],
                'unique_together': {('asset_id', 'location', 'depth_start', 'depth_end')},
            },
        ),
        migrations.CreateModel(
            name='HermeticalTestingNorm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('depth_start', models.IntegerField(help_text='Start depth in meters', validators=[django.core.validators.MinValueValidator(0)])),
                ('depth_end', models.IntegerField(help_text='End depth in meters', validators=[django.core.validators.MinValueValidator(0)])),
                ('norm_days', models.DecimalField(decimal_places=2, help_text='Norm time in days for hermetical testing', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['depth_start'],
                'unique_together': {('depth_start', 'depth_end')},
            },
        ),
    ]
