# Generated by Django 5.1.5 on 2026-01-10 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0020_operationnorm_casingnorm_coringnorm_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drillingbenchmark',
            options={'ordering': ['location', 'pool', 'well_category', 'field'], 'verbose_name': 'Drilling Benchmark', 'verbose_name_plural': 'Drilling Benchmarks'},
        ),
        migrations.AlterUniqueTogether(
            name='drillingbenchmark',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='drillingbenchmark',
            name='location',
            field=models.CharField(default='Cambay', help_text='Location name (e.g., Cambay)', max_length=100),
        ),
        migrations.AddField(
            model_name='drillingbenchmark',
            name='well_depth_end',
            field=models.IntegerField(default=0, help_text='Well depth end in meters', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='drillingbenchmark',
            name='well_depth_start',
            field=models.IntegerField(default=0, help_text='Well depth start in meters', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='drillingbenchmark',
            name='pool',
            field=models.CharField(default='AK', help_text='Pool name (e.g., AK, AV, KT)', max_length=100),
        ),
        migrations.AlterField(
            model_name='drillingbenchmark',
            name='well_category',
            field=models.CharField(choices=[('Directional', 'Directional'), ('Vertical', 'Vertical'), ('Sidetrack', 'Sidetrack')], default='Directional', help_text='Category of well', max_length=50),
        ),
        migrations.RemoveField(
            model_name='drillingbenchmark',
            name='depth_range',
        ),
    ]
