# Generated by Django 5.1.5 on 2026-01-10 08:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0021_alter_drillingbenchmark_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionTestingNorm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(help_text='Location/Asset name', max_length=255)),
                ('well_depth_start', models.IntegerField(help_text='Well depth interval start in meters')),
                ('well_depth_end', models.IntegerField(help_text='Well depth interval end in meters')),
                ('well_type', models.CharField(choices=[('Development', 'Development'), ('Exploratory', 'Exploratory')], help_text='Well type', max_length=50)),
                ('days', models.DecimalField(decimal_places=1, help_text='Number of days for completion testing', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Completion Testing Norm',
                'verbose_name_plural': 'Completion Testing Norms',
                'ordering': ['location', 'well_depth_start', 'well_type'],
            },
        ),
    ]
