# Generated by Django 5.1.5 on 2026-01-12 05:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0022_completiontestingnorm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job', models.TextField(help_text='Job description')),
                ('norm_time', models.CharField(help_text='Norm time for the job', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Additional Test',
                'verbose_name_plural': 'Additional Tests',
                'ordering': ['job'],
            },
        ),
    ]
