# Generated by Django 5.1.5 on 2026-01-15 08:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0023_additionaltest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fund_centre', models.CharField(help_text='Fund Centre code', max_length=50)),
                ('company_code', models.CharField(help_text='Company Code', max_length=50)),
                ('cost_centre', models.CharField(help_text='Cost Centre', max_length=50)),
                ('category', models.CharField(help_text='Category (Asset/Basin/Plant/Other)', max_length=100)),
                ('name', models.CharField(help_text='Name of the entity', max_length=255)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(help_text='State', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Code',
                'verbose_name_plural': 'Company Codes',
                'ordering': ['company_code', 'name'],
                'unique_together': {('fund_centre', 'cost_centre')},
            },
        ),
    ]
