# Generated by Django 5.1.5 on 2026-01-15 09:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0024_companycode'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPersonnelInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpf_no', models.CharField(help_text='CPF Number', max_length=20, unique=True)),
                ('crc', models.CharField(blank=True, help_text='CRC', max_length=50, null=True)),
                ('duty_type', models.CharField(blank=True, help_text='Duty Type', max_length=50, null=True)),
                ('work_pattern', models.CharField(blank=True, help_text='Work Pattern', max_length=50, null=True)),
                ('pwd', models.CharField(blank=True, help_text='PwD', max_length=10, null=True)),
                ('q_new', models.CharField(blank=True, help_text='Q New', max_length=50, null=True)),
                ('org_unit', models.CharField(blank=True, help_text='ORG.UNIT', max_length=50, null=True)),
                ('group_1', models.CharField(blank=True, help_text='GROUP 1', max_length=100, null=True)),
                ('group_2', models.CharField(blank=True, help_text='GROUP 2', max_length=100, null=True)),
                ('org_new', models.CharField(blank=True, help_text='ORG NEW', max_length=100, null=True)),
                ('org_unit_text', models.CharField(blank=True, help_text='ORG.UNIT TEXT', max_length=255, null=True)),
                ('position_text', models.CharField(blank=True, help_text='POSITION TEXT', max_length=255, null=True)),
                ('location', models.CharField(blank=True, help_text='LOCATION', max_length=100, null=True)),
                ('sector', models.CharField(blank=True, help_text='SECTOR', max_length=100, null=True)),
                ('name', models.CharField(help_text='NAME', max_length=255)),
                ('designation', models.CharField(blank=True, help_text='DESIGNATION', max_length=100, null=True)),
                ('lvl', models.CharField(blank=True, help_text='LVL', max_length=20, null=True)),
                ('disp', models.CharField(blank=True, help_text='DISP', max_length=100, null=True)),
                ('subdisp', models.CharField(blank=True, help_text='SUBDISP', max_length=100, null=True)),
                ('category', models.CharField(blank=True, help_text='CATEGORY', max_length=50, null=True)),
                ('gender_key', models.CharField(blank=True, help_text='GENDER KEY', max_length=10, null=True)),
                ('dob', models.DateField(blank=True, help_text='Date of Birth', null=True)),
                ('dor', models.DateField(blank=True, help_text='Date of Retirement', null=True)),
                ('doj_ongc', models.DateField(blank=True, help_text='Date of Join ONGC', null=True)),
                ('date_of_join_post', models.DateField(blank=True, help_text='Date of Join Post', null=True)),
                ('eff_date_prom', models.DateField(blank=True, help_text='Effective Date of Promotion', null=True)),
                ('date_of_join_per_area', models.DateField(blank=True, help_text='Date of Join Personal Area', null=True)),
                ('date_of_join_position', models.DateField(blank=True, help_text='Date of Join Position', null=True)),
                ('date_of_retirement', models.DateField(blank=True, help_text='Date of Retirement', null=True)),
                ('personal_area', models.CharField(blank=True, help_text='PERSONAL AREA', max_length=100, null=True)),
                ('state_deployed', models.CharField(blank=True, help_text='STATE DEPLOYED', max_length=100, null=True)),
                ('qual_text', models.CharField(blank=True, help_text='QUAL_TEXT', max_length=255, null=True)),
                ('home_state', models.CharField(blank=True, help_text='HOME STATE', max_length=100, null=True)),
                ('dl_designation_text', models.CharField(blank=True, help_text='DL-DESIGNATION TEXT', max_length=255, null=True)),
                ('dl_discipline_text', models.CharField(blank=True, help_text='DL-DISCIPLINE TEXT', max_length=255, null=True)),
                ('dl_sub_disp_text', models.CharField(blank=True, help_text='DL-SUB DISP TEXT', max_length=255, null=True)),
                ('type_i', models.CharField(blank=True, help_text='Type-I', max_length=50, null=True)),
                ('mobile_no', models.CharField(blank=True, help_text='Mobile Number', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Master Personnel Info',
                'verbose_name_plural': 'Master Personnel Info',
                'ordering': ['name', 'cpf_no'],
                'indexes': [models.Index(fields=['cpf_no'], name='scheduler_m_cpf_no_03df27_idx'), models.Index(fields=['name'], name='scheduler_m_name_7bfbdd_idx'), models.Index(fields=['location'], name='scheduler_m_locatio_6c4a2d_idx')],
            },
        ),
    ]
