# Generated by Django 5.1.5 on 2026-01-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0025_masterpersonnelinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterpersonnelinfo',
            name='category',
        ),
    ]
