# Generated by Django 5.1.5 on 2026-01-15 09:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0026_remove_category_from_mpi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpf_no', models.CharField(blank=True, help_text='CPF Number (linked to MPI)', max_length=20, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('L1', 'L1'), ('user', 'User')], default='user', help_text='User role: admin, L1, or user', max_length=10)),
                ('assigned_location', models.CharField(blank=True, help_text="Location assigned to user (for 'user' role)", max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this role assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_user_roles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='Django user account', on_delete=django.db.models.deletion.CASCADE, related_name='role_assignment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'ordering': ['user__username'],
                'indexes': [models.Index(fields=['cpf_no'], name='scheduler_u_cpf_no_e05564_idx'), models.Index(fields=['role'], name='scheduler_u_role_b68a68_idx')],
            },
        ),
    ]
