# Generated by Django 5.1.5 on 2026-01-15 11:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0027_userrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['user__username'], 'verbose_name': 'User Role (Deprecated)', 'verbose_name_plural': 'User Roles (Deprecated)'},
        ),
        migrations.CreateModel(
            name='AuthorizedUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpf_no', models.CharField(db_index=True, help_text='CPF Number (Employee ID) - used as username for LDAP', max_length=20, unique=True)),
                ('name', models.CharField(blank=True, help_text='Full name from MPI', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email from LDAP', max_length=254, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('L1', 'L1'), ('user', 'User')], default='user', help_text='User role: admin, L1, or user', max_length=10)),
                ('assigned_location', models.CharField(blank=True, help_text="Location assigned to user (for 'user' role)", max_length=100, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only active users can log in')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, help_text='Last successful LDAP login', null=True)),
            ],
            options={
                'verbose_name': 'Authorized User',
                'verbose_name_plural': 'Authorized Users',
                'ordering': ['cpf_no'],
                'indexes': [models.Index(fields=['cpf_no', 'is_active'], name='scheduler_a_cpf_no_7f475b_idx'), models.Index(fields=['role'], name='scheduler_a_role_83a44e_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, help_text='Username/CPF used in login attempt', max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed_ldap', 'Failed - Invalid LDAP Credentials'), ('failed_unauthorized', 'Failed - User Not Authorized'), ('failed_inactive', 'Failed - User Inactive'), ('failed_error', 'Failed - System Error')], help_text='Result of login attempt', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of login attempt', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details (not shown to user)', null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the login attempt occurred')),
                ('user', models.ForeignKey(blank=True, help_text='Django user (if login was successful)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Attempt',
                'verbose_name_plural': 'Login Attempts',
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['-attempted_at'], name='scheduler_l_attempt_6e7206_idx'), models.Index(fields=['username', '-attempted_at'], name='scheduler_l_usernam_613266_idx'), models.Index(fields=['status', '-attempted_at'], name='scheduler_l_status_1a3b10_idx')],
            },
        ),
    ]
