# Generated by Django 5.1.5 on 2026-01-15 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0028_alter_userrole_options_authorizeduser_loginattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizeduser',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Linked Django User account (created after LDAP auth)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
