# Generated by Django 5.1.5 on 2026-01-16 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0030_companycode_location_centralization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rig',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location (Company Code) where this rig is assigned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rigs', to='scheduler.companycode'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location (Company Code) this schedule belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='scheduler.companycode'),
        ),
        migrations.AlterField(
            model_name='stagedwell',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location (Company Code) where this well is located', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_wells', to='scheduler.companycode'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location (Company Code) this user belongs to. If empty, user can see all locations (admin).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='scheduler.companycode'),
        ),
        migrations.AlterField(
            model_name='well',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location (Company Code) where this well is located', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wells', to='scheduler.companycode'),
        ),
    ]
