# Generated by Django 5.1.5 on 2026-01-16 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0032_location_standardization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rigbuildingnorm',
            options={'ordering': ['location', 'rig_name'], 'verbose_name': 'Rig Building Norm', 'verbose_name_plural': 'Rig Building Norms'},
        ),
        migrations.AddField(
            model_name='rigbuildingnorm',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location (Company Code) for this rig building norm', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rig_building_norms', to='scheduler.companycode'),
        ),
        migrations.AlterField(
            model_name='rigbuildingnorm',
            name='rig_name',
            field=models.CharField(help_text='Name of the rig (e.g., E-760, Mobile rigs, IPS-M700)', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='rigbuildingnorm',
            unique_together={('location', 'rig_name')},
        ),
    ]
