# Generated by Django 5.1.5 on 2026-01-16 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0033_add_location_to_rig_building_norm'),
    ]

    operations = [
        # First, remove the old unique_together constraint
        migrations.AlterUniqueTogether(
            name='dailydrillingrate',
            unique_together=set(),
        ),
        # Add the field column
        migrations.AddField(
            model_name='dailydrillingrate',
            name='field',
            field=models.ForeignKey(blank=True, help_text='Field/Sector from CompanyCode (e.g., Akholjuni, Anklav)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_drilling_rates_field', to='scheduler.companycode'),
        ),
        # Alter location field
        migrations.AlterField(
            model_name='dailydrillingrate',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location from CompanyCode (e.g., CAMBAY, MEHSANA)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_drilling_rates_location', to='scheduler.companycode'),
        ),
        # Remove asset_id field
        migrations.RemoveField(
            model_name='dailydrillingrate',
            name='asset_id',
        ),
        # Update model options
        migrations.AlterModelOptions(
            name='dailydrillingrate',
            options={'ordering': ['location', 'field', 'depth_start']},
        ),
        # Add new unique_together constraint
        migrations.AlterUniqueTogether(
            name='dailydrillingrate',
            unique_together={('location', 'field', 'depth_start', 'depth_end')},
        ),
    ]
