# Generated by Django 5.1.5 on 2026-01-16 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0034_rename_daily_drilling_rate_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rigbuildingadjustment',
            options={'ordering': ['location', 'category', 'priority', 'condition'], 'verbose_name': 'Rig Building Adjustment', 'verbose_name_plural': 'Rig Building Adjustments'},
        ),
        migrations.AddField(
            model_name='rigbuildingadjustment',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location (Company Code) for this adjustment rule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rig_building_adjustments', to='scheduler.companycode'),
        ),
    ]
