# Generated by Django 5.1.5 on 2026-01-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0035_add_location_to_rigbuildingadjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydrillingrate',
            name='field',
            field=models.CharField(blank=True, help_text='Field/Sector name (free text, e.g., Akholjuni, Anklav)', max_length=100, null=True),
        ),
    ]
