# Generated by Django 5.1.5 on 2026-01-16 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0037_add_location_to_additional_ops_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaltest',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Location from Company Codes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_tests', to='scheduler.companycode'),
        ),
        migrations.AlterField(
            model_name='operationnorm',
            name='operation',
            field=models.CharField(help_text='Name of the operation', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='additionaltest',
            unique_together={('location', 'job')},
        ),
    ]
