# Generated by Django 5.1.5 on 2026-01-17 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0038_add_location_to_additional_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagedwell',
            name='drl_days',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Drilling days required - to be completed by user', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='stagedwell',
            name='pt_days',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Post-drilling testing days - to be completed by user', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
