# Generated by Django 5.1.5 on 2026-01-20 07:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0039_change_drl_pt_days_to_decimal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WellBasket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name/description for this basket', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes for this basket', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FINALIZED', 'Finalized'), ('ARCHIVED', 'Archived')], default='ACTIVE', help_text='Current status of the basket', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this basket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_baskets', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(help_text='Location (Company Code) this basket belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='well_baskets', to='scheduler.companycode')),
            ],
            options={
                'verbose_name': 'Well Basket',
                'verbose_name_plural': 'Well Baskets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stagedwell',
            name='basket',
            field=models.ForeignKey(blank=True, help_text='Basket this well belongs to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_wells', to='scheduler.wellbasket'),
        ),
    ]
