# Generated by Django 5.1.5 on 2026-01-20 12:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0040_wellbasket_stagedwell_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellPairDistance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distance_km', models.DecimalField(decimal_places=3, help_text='Distance between wells in kilometers', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(help_text='Location (Company Code) for this distance calculation', on_delete=django.db.models.deletion.CASCADE, related_name='well_pair_distances', to='scheduler.companycode')),
                ('rig', models.ForeignKey(help_text='Rig associated with these wells', on_delete=django.db.models.deletion.CASCADE, related_name='well_pair_distances', to='scheduler.rig')),
                ('well_1', models.ForeignKey(help_text='First well in the pair', on_delete=django.db.models.deletion.CASCADE, related_name='distances_as_well_1', to='scheduler.well')),
                ('well_2', models.ForeignKey(help_text='Second well in the pair', on_delete=django.db.models.deletion.CASCADE, related_name='distances_as_well_2', to='scheduler.well')),
            ],
            options={
                'verbose_name': 'Well Pair Distance',
                'verbose_name_plural': 'Well Pair Distances',
                'ordering': ['location__company_code', 'rig__name', 'well_1__name', 'well_2__name'],
                'unique_together': {('rig', 'well_1', 'well_2')},
            },
        ),
    ]
