# Generated by Django 5.1.5 on 2026-01-22 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0041_well_pair_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='rig',
            name='rig_building_norm',
            field=models.ForeignKey(blank=True, help_text='Associated rig building norm for this rig', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rigs', to='scheduler.rigbuildingnorm'),
        ),
        migrations.AlterField(
            model_name='wellpairdistance',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, help_text='Distance between wells in metres', max_digits=10),
        ),
    ]
