# Generated by Django 5.1.5 on 2026-01-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0042_rig_rig_building_norm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydrillingrate',
            name='casing_deviation_tag',
            field=models.CharField(choices=[('2CP', '2CP'), ('3CP', '3CP'), ('3CP & DH', '(3CP & DH)')], default='2CP', help_text='Casing-Deviation Tag (2CP, 3CP, or 3CP & DH)', max_length=20),
        ),
        migrations.AddField(
            model_name='drillingbenchmark',
            name='casing_deviation_tag',
            field=models.CharField(choices=[('2CP', '2CP'), ('3CP', '3CP'), ('3CP & DH', '(3CP & DH)')], default='2CP', help_text='Casing-Deviation Tag (2CP, 3CP, or 3CP & DH)', max_length=20),
        ),
    ]
