# Generated by Django 5.1.5 on 2026-01-29 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0043_add_casing_deviation_tag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailydrillingrate',
            unique_together={('location', 'field', 'depth_start', 'depth_end', 'casing_deviation_tag')},
        ),
    ]
