# Generated by Django 5.1.5 on 2026-01-30 07:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0046_rename_casing_deviation_tag_to_loc_spec_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSpecFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('factor_value', models.CharField(help_text="The factor value (e.g., '2CP', '3CP', 'Main Pool', 'other than Main')", max_length=50)),
                ('display_order', models.IntegerField(default=0, help_text='Order for display in dropdowns')),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default value for the location')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this factor is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(help_text='Location (Company Code) for this factor', on_delete=django.db.models.deletion.CASCADE, related_name='loc_spec_factors', to='scheduler.companycode')),
            ],
            options={
                'verbose_name': 'Location Spec Factor',
                'verbose_name_plural': 'Location Spec Factors',
                'ordering': ['location', 'display_order', 'factor_value'],
                'unique_together': {('location', 'factor_value')},
            },
        ),
    ]
