# Generated by Django 5.1.5 on 2026-01-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0047_add_location_spec_factor_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydrillingrate',
            name='loc_spec_factor',
            field=models.CharField(blank=True, help_text='Location-specific factor (dynamically managed via Location Spec Factors)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drillingbenchmark',
            name='loc_spec_factor',
            field=models.CharField(blank=True, help_text='Location-specific factor (dynamically managed via Location Spec Factors)', max_length=50, null=True),
        ),
    ]
