# Generated by Django 5.1.5 on 2026-01-30 14:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0048_remove_loc_spec_factor_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='ilm_days',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='ILM days to reach this well from previous well', max_digits=5),
        ),
    ]
