# Generated by Django 5.1.5 on 2026-02-05 04:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0049_add_ilm_days_to_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTutorial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the video tutorial', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of what the video covers')),
                ('category', models.CharField(choices=[('getting_started', 'Getting Started'), ('scheduling', 'Scheduling'), ('data_management', 'Data Management'), ('reports', 'Reports & Analytics'), ('admin', 'Admin Features'), ('other', 'Other')], default='other', help_text='Category of the tutorial', max_length=50)),
                ('video_file', models.FileField(help_text='Video file (max 1GB)', upload_to='tutorials/videos/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail image for the video', null=True, upload_to='tutorials/thumbnails/')),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Duration of video in minutes', null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this video is visible to users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(default=0, help_text='Number of times this video has been viewed')),
                ('uploaded_by', models.ForeignKey(help_text='Admin who uploaded this video', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_tutorials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Tutorial',
                'verbose_name_plural': 'Video Tutorials',
                'ordering': ['category', 'order', 'title'],
            },
        ),
    ]
