# Generated by Django 5.1.5 on 2026-02-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0050_add_video_tutorial_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotutorial',
            name='compressed_size_mb',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Compressed file size in MB', max_digits=10),
        ),
        migrations.AddField(
            model_name='videotutorial',
            name='compressed_video',
            field=models.FileField(blank=True, help_text='Compressed version for smaller file size', null=True, upload_to='tutorials/videos/'),
        ),
        migrations.AddField(
            model_name='videotutorial',
            name='optimized_size_mb',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Optimized file size in MB', max_digits=10),
        ),
        migrations.AddField(
            model_name='videotutorial',
            name='optimized_video',
            field=models.FileField(blank=True, help_text='Optimized version for fast streaming', null=True, upload_to='tutorials/videos/'),
        ),
        migrations.AddField(
            model_name='videotutorial',
            name='original_size_mb',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Original file size in MB', max_digits=10),
        ),
        migrations.AddField(
            model_name='videotutorial',
            name='processing_error',
            field=models.TextField(blank=True, help_text='Error message if processing failed'),
        ),
        migrations.AddField(
            model_name='videotutorial',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Video processing status', max_length=20),
        ),
        migrations.AlterField(
            model_name='videotutorial',
            name='video_file',
            field=models.FileField(help_text='Video file (max 1GB) - will be automatically optimized', upload_to='tutorials/videos/'),
        ),
    ]
