# Generated by Django 5.1.5 on 2026-02-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0052_add_created_by_to_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagedwell',
            name='basket',
        ),
        migrations.AddField(
            model_name='stagedwell',
            name='baskets',
            field=models.ManyToManyField(blank=True, help_text='Baskets this well belongs to', related_name='staged_wells', to='scheduler.wellbasket'),
        ),
    ]
