# Generated by Django 5.1.5 on 2026-02-23 06:13

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0053_staged_well_baskets_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Execution schedule name', max_length=200)),
                ('financial_year', models.CharField(help_text='Financial Year (e.g., 2025-2026)', max_length=9)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=15)),
                ('cutoff_date', models.DateField(blank=True, help_text='All wells before this date are considered locked', null=True)),
                ('total_planned_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('total_actual_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('projected_end_date', models.DateField(blank=True, null=True)),
                ('optimization_runs', models.IntegerField(default=0, help_text='Number of re-optimization runs')),
                ('last_optimized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_executions', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, help_text='Location (Company Code) for this execution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_schedules', to='scheduler.companycode')),
                ('source_schedule', models.ForeignKey(help_text='Original approved schedule this execution is based on', on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='scheduler.schedule')),
            ],
            options={
                'verbose_name': 'Execution Schedule',
                'verbose_name_plural': 'Execution Schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ACTIVATED', 'Schedule Activated'), ('ACTUAL_SET', 'Actual Dates Set'), ('LOCKED', 'Well Locked'), ('CUTOFF_APPLIED', 'Cutoff Lock Applied'), ('WELL_ADDED', 'Well Added'), ('WELL_REMOVED', 'Well Removed'), ('RIG_ADDED', 'Rig Added'), ('RIG_REMOVED', 'Rig Removed'), ('REOPTIMIZED', 'Re-optimization Run'), ('STATUS_CHANGE', 'Status Changed'), ('DEFERRED', 'Well Deferred')], max_length=20)),
                ('description', models.TextField(help_text='Human-readable description of the action')),
                ('details', models.JSONField(blank=True, default=dict, help_text='JSON details of the action (well/rig IDs, dates, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to=settings.AUTH_USER_MODEL)),
                ('execution_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='scheduler.executionschedule')),
            ],
            options={
                'verbose_name': 'Execution Log',
                'verbose_name_plural': 'Execution Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionRig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rig is active in execution')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('rig', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_rigs', to='scheduler.rig')),
                ('execution_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_rigs', to='scheduler.executionschedule')),
            ],
            options={
                'verbose_name': 'Execution Rig',
                'verbose_name_plural': 'Execution Rigs',
                'unique_together': {('execution_schedule', 'rig')},
            },
        ),
        migrations.CreateModel(
            name='ExecutionWell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('planned_start_date', models.DateField(help_text='Planned/optimized start date')),
                ('planned_end_date', models.DateField(help_text='Planned/optimized end date')),
                ('actual_start_date', models.DateField(blank=True, help_text='Actual drilling start date', null=True)),
                ('actual_end_date', models.DateField(blank=True, help_text='Actual drilling end date', null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('LOCKED', 'Locked'), ('DEFERRED', 'Deferred'), ('REMOVED', 'Removed')], default='PLANNED', max_length=15)),
                ('is_locked', models.BooleanField(db_index=True, default=False, help_text='Locked wells cannot be moved and act as constraints for re-optimization')),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('sequence_order', models.IntegerField(help_text="Order within rig's sequence")),
                ('planned_drilling_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('actual_drilling_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('planned_ilm_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('actual_ilm_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_wells', to='scheduler.executionschedule')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_execution_wells', to=settings.AUTH_USER_MODEL)),
                ('rig', models.ForeignKey(help_text='Currently assigned rig', on_delete=django.db.models.deletion.PROTECT, related_name='execution_well_assignments', to='scheduler.rig')),
                ('source_assignment', models.ForeignKey(blank=True, help_text='Original assignment from the source schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_wells', to='scheduler.assignment')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_wells', to='scheduler.well')),
            ],
            options={
                'verbose_name': 'Execution Well',
                'verbose_name_plural': 'Execution Wells',
                'ordering': ['rig__name', 'sequence_order'],
                'unique_together': {('execution_schedule', 'well')},
            },
        ),
    ]
