# Generated by Django 5.1.5 on 2026-02-25 11:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0054_executionschedule_executionlog_executionrig_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, default='', help_text='Username snapshot (preserved even if user is deleted)', max_length=150)),
                ('category', models.CharField(choices=[('AUTH', 'Authentication'), ('PAGE_VIEW', 'Page View'), ('DATA_CREATE', 'Data Create'), ('DATA_UPDATE', 'Data Update'), ('DATA_DELETE', 'Data Delete'), ('DATA_IMPORT', 'Data Import'), ('DATA_EXPORT', 'Data Export'), ('SCHEDULE', 'Scheduling'), ('EXECUTION', 'Execution'), ('ADMIN', 'Administration'), ('API', 'API Call'), ('SYSTEM', 'System Event')], db_index=True, max_length=20)),
                ('action', models.CharField(help_text="Short action description e.g. 'User Login', 'Created Well'", max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description of the action')),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='Browser/client user agent string')),
                ('request_method', models.CharField(blank=True, default='', help_text='HTTP method (GET, POST, etc.)', max_length=10)),
                ('request_path', models.CharField(blank=True, default='', help_text='URL path accessed', max_length=500)),
                ('target_model', models.CharField(blank=True, default='', help_text="Model/entity affected e.g. 'Well', 'Rig', 'User'", max_length=100)),
                ('target_id', models.CharField(blank=True, default='', help_text='ID of the affected object', max_length=255)),
                ('target_name', models.CharField(blank=True, default='', help_text='Display name of affected object', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured data about the action')),
                ('session_key', models.CharField(blank=True, default='', help_text='Session key for correlating actions', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='scheduler_u_user_id_1ac8fc_idx'), models.Index(fields=['category', '-created_at'], name='scheduler_u_categor_03385c_idx'), models.Index(fields=['ip_address', '-created_at'], name='scheduler_u_ip_addr_65a49a_idx'), models.Index(fields=['target_model', '-created_at'], name='scheduler_u_target__2068f6_idx')],
            },
        ),
    ]
