# Generated by Django 5.1.5 on 2026-02-28 19:30

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0055_useractivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionlog',
            name='action',
            field=models.CharField(choices=[('ACTIVATED', 'Schedule Activated'), ('ACTUAL_SET', 'Actual Dates Set'), ('LOCKED', 'Well Locked'), ('CUTOFF_APPLIED', 'Cutoff Lock Applied'), ('WELL_ADDED', 'Well Added'), ('WELL_REMOVED', 'Well Removed'), ('WELL_REPLACED', 'Well Replaced'), ('RIG_ADDED', 'Rig Added'), ('RIG_REMOVED', 'Rig Removed'), ('RIG_REPLACED', 'Rig Replaced'), ('REOPTIMIZED', 'Re-optimization Run'), ('STATUS_CHANGE', 'Status Changed'), ('DEFERRED', 'Well Deferred'), ('DATES_SHIFTED', 'Dates Shifted'), ('REMARKS_UPDATED', 'Remarks Updated'), ('SCENARIO_CREATED', 'Scenario Created'), ('SCENARIO_APPLIED', 'Scenario Applied')], max_length=25),
        ),
        migrations.CreateModel(
            name='ExecutionScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Scenario name, e.g. 'Remove Rig-5 scenario'", max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='What-if description')),
                ('snapshot', models.JSONField(default=dict, help_text='JSON snapshot: {rigs: [...], wells: [...], metrics: {...}}')),
                ('is_optimized', models.BooleanField(default=False, help_text='Was the optimizer run for this scenario?')),
                ('solver_status', models.CharField(blank=True, default='', max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('total_duration_days', models.IntegerField(default=0)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scenarios', to=settings.AUTH_USER_MODEL)),
                ('execution_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='scheduler.executionschedule')),
            ],
            options={
                'verbose_name': 'Execution Scenario',
                'verbose_name_plural': 'Execution Scenarios',
                'ordering': ['-created_at'],
            },
        ),
    ]
