# Generated by Django 5.1.5 on 2026-03-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0057_add_cancelled_status_to_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellpairdistance',
            name='ilm_days',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Pre-computed ILM days based on adjustment rules', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='wellpairdistance',
            name='ilm_note',
            field=models.CharField(blank=True, default='', help_text='Note about ILM calculation', max_length=255),
        ),
        migrations.AddField(
            model_name='wellpairdistance',
            name='ilm_rules_applied',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of rules applied during ILM calculation'),
        ),
    ]
