# Generated by Django 5.1.5 on 2026-03-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0058_add_ilm_cache_to_wellpairdistance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagedwell',
            name='rtd',
            field=models.DateField(blank=True, help_text='Ready To Drill date - can be blank on upload, set later', null=True),
        ),
    ]
