# Generated by Django 5.1.5 on 2026-03-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0059_alter_stagedwell_rtd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterpersonnelinfo',
            name='pwd',
            field=models.CharField(blank=True, help_text='PwD', max_length=50, null=True),
        ),
    ]
