# Generated by Django 5.1.5 on 2026-03-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0060_alter_masterpersonnelinfo_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='optimality_gap_percent',
            field=models.FloatField(blank=True, help_text='Optimality gap in percent. 0% = proven optimal. Small % = near-optimal.', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_hash',
            field=models.CharField(blank=True, help_text='SHA-256 fingerprint of assignments (rig, well, start, end). Used to verify determinism.', max_length=64, null=True),
        ),
    ]
