# Generated by Django 5.1.5 on 2026-03-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0061_add_optimality_gap_and_schedule_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='input_rigs_count',
            field=models.IntegerField(blank=True, help_text='Number of rigs submitted for optimization', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='input_wells_count',
            field=models.IntegerField(blank=True, help_text='Number of wells submitted for optimization', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_limit_seconds',
            field=models.IntegerField(blank=True, help_text='Solver time limit in seconds as requested by user', null=True),
        ),
    ]
