# Generated by Django 5.1.5 on 2026-09-04 10:30
"""Determinism provenance on Schedule (deterministic-schedule-fix, task 8.2).

Six columns recording *why* a schedule is or is not reproducible, to sit
alongside ``schedule_hash`` (migration 0061) which records *which* schedule it
is.

Deployment properties, all deliberate:

* **Additive.** Six ``AddField`` operations and nothing else. No column is
  altered, renamed or dropped, so no existing read or write path can be
  invalidated by applying it.
* **Nullable, no default, no backfill.** Rows created before this migration have
  no provenance, and a null says exactly that. Inventing values would be worse
  than admitting the gap — in particular ``deterministic_stop`` is a *nullable*
  Boolean rather than one defaulting to ``False``, so "not recorded" can never be
  misread as "not reproducible".
* **Reversible.** ``AddField`` is auto-reversible: Django derives the
  ``RemoveField`` for each, so ``migrate scheduler 0062`` rolls this back
  cleanly. No ``RunPython`` and no ``reverse_code=noop`` anywhere, which is what
  would make a rollback lossy.
* **No table rewrite.** Adding a nullable column with no default is a metadata-only
  change on PostgreSQL, so it does not rewrite the ``scheduler_schedule`` table
  and does not hold a long lock.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0062_add_schedule_input_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='deterministic_budget',
            field=models.FloatField(blank=True, help_text='Deterministic-time units the solve was allowed. Null on the performance path, which is given no work budget.', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='deterministic_stop',
            field=models.BooleanField(blank=True, help_text='ADVISORY. True when the solve stopped on its work budget rather than the wall clock. A single run cannot prove reproducibility; the authoritative check is the check_determinism command.', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='deterministic_time_used',
            field=models.FloatField(blank=True, help_text='Deterministic-time units consumed by the solve. A work counter, not seconds, so it is independent of machine load.', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='model_fingerprint',
            field=models.CharField(blank=True, help_text='SHA-256 of the CP-SAT model proto. Identifies the question put to the solver; two runs are only comparable if this matches.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='solver_fingerprint',
            field=models.CharField(blank=True, help_text='SHA-256 of the solver parameters, OR-Tools version and determinism settings. Identifies the machinery used to answer.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='stop_reason',
            field=models.CharField(blank=True, help_text='Why the solver stopped: OPTIMAL_PROVEN, DETERMINISTIC_BUDGET, WALL_CLOCK_BACKSTOP, INFEASIBLE or OTHER.', max_length=32, null=True),
        ),
    ]
